# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

# git remote add origin https://${GIT_ACCOUNT_TOKEN}@${REPO_TARGET}

name: Build All

on:
  push:
    branches:    
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: 1. Setup Node.js ${{ matrix.node-version }} ...
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: 2 Prepare empty folder ...
      run:
        mkdir output

    - name: 3.1 Checkout blog source code ...
      env:
        REPO_TARGET: github.com/we-ready/blog.git
      run:
        git clone --depth=1 -b main https://${REPO_TARGET} ./blog

    - name: 3.2 Build blog ...
      env:
        CI: false
      run: |
        cd ./blog
        npm install
        npm run build --if-present
        rm -rf ./public/*.map
        rm -rf ./public/*.txt
        cd ../

    - name: 3.3 Deploy result ...
      run:
        cp -r ./blog/public/. ./output

    - name: 4.1 Checkout argus/storybook source code ...
      env:
        REPO_TARGET: github.com/we-ready/argus.git
        GIT_ACCOUNT_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN_OF_WE_READY }}
      run:
        git clone --depth=1 -b main https://${GIT_ACCOUNT_TOKEN}@${REPO_TARGET} ./argus

    - name: 4.2 Build argus/storybook ...
      env:
        CI: false
      run: |
        cd ./argus/npmlib/components/storybook
        npm install
        npm run build-storybook --if-present
        mv ./storybook-static/index.html ./storybook-static/storybook.html
        rm -rf ./storybook-static/*.map
        rm -rf ./storybook-static/*.txt
        cd ../../../../

    - name: 4.3 Deploy result ...
      run:
        cp -r ./argus/npmlib/components/storybook/storybook-static/. ./output

    - name: 5 Deploy to weready repo ...
      env:
        REPO_TARGET: github.com/we-ready/we-ready.github.io.git
        GIT_ACCOUNT_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN_OF_WE_READY }}
      run: |
        git clone --depth=1 -b master https://${GIT_ACCOUNT_TOKEN}@${REPO_TARGET} ./weready
        cd ./weready
        find ! -regex '^./.git\(/.*\)?' -delete
        cp ../output/. ./
        git config --global user.email "yunzhi.wei@qq.com"
        git config --global user.name "we-ready"
        git add -A
        git commit -m "Update by github workflow actions"
        git push origin master
